apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-bootloader
spec:
  replicas: 1
  selector:
    matchLabels:
      airbyte: bootloader
  template:
    metadata:
      labels:
        airbyte: bootloader
    spec:
      containers:
        - name: airbyte-bootloader-container
          image: airbyte/bootloader
          env:
            - name: AIRBYTE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: AIRBYTE_VERSION
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: DATABASE_PORT
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airbyte-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: airbyte-env
                  key: DATABASE_URL
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: airbyte-secrets
                  key: DATABASE_USER
